version: '3'

services:

  prometheus:
    image: prom/prometheus:v2.25.2
#    ports:
#      - 9090:9090
    volumes:
      - ./prometheus_config:/etc/prometheus
    networks:
      - monitoring
    restart: always

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.18.0
    networks:
      - monitoring
    restart: always

  node_exporter:
    image: prom/node-exporter:v1.1.2
    networks:
      - monitoring
    restart: always

  loki:
    image: grafana/loki:2.2.0
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
    restart: always

  promtail:
    image: grafana/promtail:2.2.0
    volumes: # Add your nginx log path and promtail configuration
      - ../private-proxy-docker/logs/:/var/log/private
      - ../../public/public-proxy-docker/logs/:/var/log/public
      - ./promtail_config:/etc/promtail/
    command: -config.file=/etc/promtail/nginx.yaml
    networks:
      - monitoring
    restart: always

  grafana:
    image: grafana/grafana:7.5.1
    environment:
      - GF_SERVER_ROOT_URL=${grafana_root_url}
      - GF_SECURITY_ADMIN_PASSWORD=${grafana_admin_pass}
    volumes:
      - "./grafana_data:/var/lib/grafana"
    networks:
      - monitoring
    restart: always
networks:
  monitoring:
    driver: bridge
